const { chromium } = (await import('/home/james/swat/projects/pc-set-up/node_modules/playwright/index.js')).default;
import fs from 'node:fs';
const gate = fs.readFileSync(new URL('./gate.txt', import.meta.url), 'utf8').trim();
const base = 'https://swat-website-storefront.vercel.app';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addCookies([{ name: 'swat_gate', value: gate, url: base }]);
const p = await ctx.newPage();
await p.goto(`${base}/book/mighty-5-utah-from-las-vegas/`, { waitUntil: 'networkidle' });
await p.screenshot({ path: 'book-1440.png', fullPage: false });
const info = await p.evaluate(() => ({ h: document.documentElement.scrollHeight, text: document.body.innerText.slice(0, 1500) }));
console.log(JSON.stringify(info).slice(0, 1600));
await browser.close();
