const { chromium } = (await import('/home/james/swat/projects/pc-set-up/node_modules/playwright/index.js')).default;
import fs from 'node:fs';
const gate = fs.readFileSync(new URL('./gate.txt', import.meta.url), 'utf8').trim();
const base = 'https://swat-website-storefront.vercel.app';
const [p, W = 1920] = process.argv.slice(2);
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: +W, height: 1000 } });
await ctx.addCookies([{ name: 'swat_gate', value: gate, url: base }]);
const page = await ctx.newPage();
await page.goto(base + p, { waitUntil: 'load' });
await page.addStyleTag({ content: '*{content-visibility:visible!important}' });
await page.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 700) { scrollTo(0, y); await new Promise(r => setTimeout(r, 60)); } scrollTo(0, 0); });
await page.waitForTimeout(800);
const out = await page.evaluate(() => {
  const R = e => { const b = e.getBoundingClientRect(); return [Math.round(b.x), Math.round(b.y + scrollY), Math.round(b.width), Math.round(b.height)]; };
  const main = document.querySelector('main');
  const cards = [...main.querySelectorAll('article')].map(a => ({ box: R(a), text: a.innerText.split('\n').filter(Boolean), img: a.querySelector('img')?.src, href: a.querySelector('a')?.getAttribute('href') }));
  const imgs = [...main.querySelectorAll('img')].map(i => ({ box: R(i), src: i.src, alt: i.alt }));
  const blocks = [...main.querySelectorAll('h1,h2,h3,h4,p,li,figcaption,blockquote')].filter(e => !e.closest('article')).map(e => ({ tag: e.tagName, box: R(e), text: e.innerText.slice(0, 1200) }));
  return { href: location.href, docH: document.documentElement.scrollHeight, cards, imgs, blocks };
});
fs.writeFileSync(new URL(`./content${p.replace(/\//g, '_')}${W}.json`, import.meta.url), JSON.stringify(out, null, 1));
await browser.close();
